# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Phil Quinn
tagline:          'Tagline goes here'
description:      'Lorem whatsem'
url:              ''
baseurl:          /
include:          ["_pages"]

author:
  name:           'Phil Quinn'
  url:            ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/quinnphil/
